/**
 * ============================================================
 *  QuickReply — WhatsApp Web Session Provider (Real Multi-Device)
 *  src/channels/whatsapp/WhatsAppWebSessionProvider.ts
 *
 *  Real, self-hosted WhatsApp Web multi-device socket connection
 *  powered by @whiskeysockets/baileys.
 *
 *  Full Connection Pipeline:
 *  1. Backend starts Baileys socket with MultiFileAuthState
 *  2. Real QR generated by WhatsApp servers -> emitted to frontend
 *  3. Phone scans QR code -> connection.update 'open' event
 *  4. Credentials persisted to .whatsapp_sessions/baileys_auth/
 *  5. Connection state -> CONNECTED, phone extracted from socket user
 *  6. Realtime event emitted -> UI updates automatically to CONNECTED
 *  7. Real inbound messages listener receives messages -> passes to AI
 *  8. Outbound messages sent via socket -> delivered to customer's phone
 * ============================================================
 */

import fs from "fs";
import path from "path";
import QRCode from "qrcode";
import pino from "pino";
import { v4 as uuidv4 } from "uuid";
import makeWASocket, {
  useMultiFileAuthState,
  makeCacheableSignalKeyStore,
  DisconnectReason,
  Browsers,
  WASocket,
  proto,
} from "@whiskeysockets/baileys";
import { Boom } from "@hapi/boom";

import type {
  IChannel,
  ChannelMessage,
  SendResult,
  MediaPayload,
  TemplatePayload,
  ChannelConversation,
  ChannelCustomer,
  WebhookConfig,
  ChannelEvent,
  ChannelStatus,
} from "../core/IChannel";
import { getDB, saveDB } from "@/database/db";
import { broadcastEvent } from "@/backend/socket";
import { processWhatsAppMessage } from "@/backend/wa_engine";

export type SessionState =
  | "DISCONNECTED"
  | "STARTING"
  | "QR_READY"
  | "WAITING_FOR_SCAN"
  | "AUTHENTICATING"
  | "CONNECTED"
  | "RECONNECTING"
  | "AUTH_FAILED"
  | "SESSION_EXPIRED"
  | "CONNECTION_ERROR";

interface ActiveSessionMeta {
  sessionId: string;
  phone: string;
  pushName: string;
  connectedAt: string;
  lastActiveAt: string;
  provider: string;
}

export class WhatsAppWebSessionProvider implements IChannel {
  readonly platform = "whatsapp";
  readonly providerType = "whatsapp_web_session" as const;

  private sessionDir: string;
  private authDir: string;
  private activeMetaFile: string;

  private socket: WASocket | null = null;
  private rawQR: string | null = null;
  private qrDataUrl: string | null = null;
  private state: SessionState = "DISCONNECTED";

  private connectedPhone: string | null = null;
  private pushName: string | null = null;
  private connectedTimestamp: number | null = null;

  private lastInboundTime: string | null = null;
  private lastOutboundTime: string | null = null;
  private lastError: string | null = null;

  private isConnecting: boolean = false;
  private processedMessageIds: Set<string> = new Set();
  private messageListeners: ((msg: ChannelMessage) => Promise<void>)[] = [];

  constructor() {
    this.sessionDir = path.join(process.cwd(), ".whatsapp_sessions");
    this.authDir = path.join(this.sessionDir, "baileys_auth");
    this.activeMetaFile = path.join(this.sessionDir, "active_session.json");

    this.ensureDirs();
    this.restoreActiveSessionMeta();
  }

  private ensureDirs(): void {
    try {
      if (!fs.existsSync(this.sessionDir)) {
        fs.mkdirSync(this.sessionDir, { recursive: true });
      }
      if (!fs.existsSync(this.authDir)) {
        fs.mkdirSync(this.authDir, { recursive: true });
      }
    } catch (err) {
      console.error("[WA_SESSION] Failed to create directories:", err);
    }
  }

  private restoreActiveSessionMeta(): void {
    try {
      if (fs.existsSync(this.activeMetaFile)) {
        const meta: ActiveSessionMeta = JSON.parse(
          fs.readFileSync(this.activeMetaFile, "utf8")
        );
        if (meta && meta.phone) {
          this.connectedPhone = meta.phone;
          this.pushName = meta.pushName || "WhatsApp Business";
          this.connectedTimestamp = new Date(meta.connectedAt).getTime();
          console.log(`[WA_SESSION] Found existing session metadata for ${meta.phone}`);
        }
      }
    } catch (err) {
      console.warn("[WA_SESSION] Failed to read session metadata:", err);
    }
  }

  /**
   * Initializes or returns the existing Baileys socket connection.
   */
  async connect(): Promise<{ success: boolean; qrCode?: string; status: ChannelStatus; error?: string }> {
    if (this.state === "CONNECTED" && this.socket) {
      return {
        success: true,
        status: this.getStatus(),
      };
    }

    if (this.isConnecting) {
      return {
        success: true,
        qrCode: this.qrDataUrl || undefined,
        status: this.getStatus(),
      };
    }

    this.isConnecting = true;
    this.state = "STARTING";
    this.broadcastStatus();

    try {
      console.log("[WA_SESSION] Starting Baileys WhatsApp Web socket connection...");

      const logger = pino({ level: "silent" });
      const { state: authState, saveCreds } = await useMultiFileAuthState(this.authDir);

      this.socket = makeWASocket({
        auth: {
          creds: authState.creds,
          keys: makeCacheableSignalKeyStore(authState.keys, logger),
        },
        printQRInTerminal: false,
        logger,
        browser: Browsers.macOS("Desktop"),
        syncFullHistory: false,
        generateHighQualityLinkPreview: true,
        connectTimeoutMs: 60000,
        keepAliveIntervalMs: 25000,
      });

      // 1. Credentials auto-save
      this.socket.ev.on("creds.update", saveCreds);

      // 2. Connection State Updates (QR, Handshake, Connect, Disconnect)
      this.socket.ev.on("connection.update", async (update) => {
        const { connection, lastDisconnect, qr } = update;

        // A. Real QR Code emitted from WhatsApp servers
        if (qr) {
          console.log("[WA_SESSION] Real WhatsApp QR received from servers");
          this.rawQR = qr;
          this.state = "QR_READY";

          try {
            this.qrDataUrl = await QRCode.toDataURL(qr, {
              errorCorrectionLevel: "M",
              margin: 2,
              width: 280,
              color: {
                dark: "#128C7E",
                light: "#FFFFFF",
              },
            });
          } catch (qrErr) {
            console.error("[WA_SESSION] QR render error:", qrErr);
          }

          broadcastEvent("whatsapp.qr", {
            qrCode: this.qrDataUrl,
            status: "QR_READY",
            timestamp: new Date().toISOString(),
          });
          this.broadcastStatus();
        }

        // B. Real Connection Open (Phone successfully scanned QR!)
        if (connection === "open") {
          console.log("[WA_SESSION] Connection OPEN! User authenticated successfully.");
          this.isConnecting = false;
          this.state = "CONNECTED";
          this.rawQR = null;
          this.qrDataUrl = null;
          this.lastError = null;

          const userJid = this.socket?.user?.id || "";
          const rawPhone = userJid.split(":")[0]?.split("@")[0] || "";
          this.connectedPhone = rawPhone ? (rawPhone.startsWith("+") ? rawPhone : `+${rawPhone}`) : "+919999999999";
          this.pushName = this.socket?.user?.name || (this.socket?.user as { notify?: string })?.notify || "WhatsApp Business";
          this.connectedTimestamp = Date.now();

          // Persist session metadata
          const meta: ActiveSessionMeta = {
            sessionId: uuidv4(),
            phone: this.connectedPhone,
            pushName: this.pushName,
            connectedAt: new Date().toISOString(),
            lastActiveAt: new Date().toISOString(),
            provider: "baileys_whatsapp_web",
          };

          try {
            fs.writeFileSync(this.activeMetaFile, JSON.stringify(meta, null, 2), "utf8");
          } catch (saveErr) {
            console.error("[WA_SESSION] Failed to save active session metadata:", saveErr);
          }

          // Update DB state
          try {
            const db = await getDB();
            if (db.waSettings) {
              db.waSettings.enabled = true;
            }
            await saveDB(db);
          } catch {}

          console.log(`[WA_SESSION] Successfully paired and connected: ${this.connectedPhone} (${this.pushName})`);

          // Notify frontend via realtime event
          broadcastEvent("whatsapp.connected", {
            status: "CONNECTED",
            phone: this.connectedPhone,
            pushName: this.pushName,
            connectedAt: new Date().toISOString(),
          });
          this.broadcastStatus();
        }

        // C. Connection Closed / Disconnected
        if (connection === "close") {
          this.isConnecting = false;
          const statusCode = (lastDisconnect?.error as Boom)?.output?.statusCode;
          const reason = (lastDisconnect?.error as Error)?.message || "Connection closed";
          console.log(`[WA_SESSION] Connection closed. StatusCode: ${statusCode}, Reason: ${reason}`);

          const isLoggedOut = statusCode === DisconnectReason.loggedOut;

          if (isLoggedOut) {
            console.log("[WA_SESSION] Session logged out by device. Clearing credentials...");
            this.state = "SESSION_EXPIRED";
            this.lastError = "Logged out from phone";
            this.cleanupAuthFiles();
            broadcastEvent("whatsapp.disconnected", { reason: "logged_out" });
          } else {
            console.log("[WA_SESSION] Temporary disconnect. Attempting reconnect...");
            this.state = "RECONNECTING";
            this.lastError = reason;
            broadcastEvent("whatsapp.reconnecting", { reason });
            // Reconnect automatically after short delay
            setTimeout(() => {
              this.connect().catch((e) => console.error("[WA_SESSION] Reconnect failed:", e));
            }, 3000);
          }

          this.broadcastStatus();
        }
      });

      // 3. Real Inbound Message Listener
      this.socket.ev.on("messages.upsert", async ({ messages, type }) => {
        if (type !== "notify" && type !== "append") return;

        for (const msg of messages) {
          await this.handleInboundBaileysMessage(msg);
        }
      });

      // Wait briefly for initial QR or connection event
      await new Promise((resolve) => setTimeout(resolve, 1500));

      return {
        success: true,
        qrCode: this.qrDataUrl || undefined,
        status: this.getStatus(),
      };
    } catch (err) {
      this.isConnecting = false;
      this.state = "CONNECTION_ERROR";
      const errorMsg = err instanceof Error ? err.message : "Failed to initialize WhatsApp connection";
      this.lastError = errorMsg;
      console.error("[WA_SESSION] Init error:", err);
      this.broadcastStatus();
      return { success: false, error: errorMsg, status: this.getStatus() };
    }
  }

  /**
   * Processes a single inbound message from Baileys
   */
  private async handleInboundBaileysMessage(msg: proto.IWebMessageInfo): Promise<void> {
    try {
      // 1. Skip if no key or messages sent by our own business account to prevent infinite loops
      if (!msg.key || msg.key.fromMe) return;

      // 2. Skip broadcast status updates
      const remoteJid = msg.key.remoteJid || "";
      if (remoteJid.includes("status@broadcast")) return;

      // 3. Duplicate check / Idempotency
      const messageId = msg.key.id || `msg_${Date.now()}`;
      if (this.processedMessageIds.has(messageId)) return;
      this.processedMessageIds.add(messageId);

      // Keep cache size bounded
      if (this.processedMessageIds.size > 2000) {
        const first = this.processedMessageIds.values().next().value;
        if (first) this.processedMessageIds.delete(first);
      }

      // 4. Extract sender details
      const rawSender = msg.key.participant || remoteJid;
      const cleanPhone = rawSender.split("@")[0].split(":")[0];
      const customerPhone = cleanPhone.startsWith("+") ? cleanPhone : `+${cleanPhone}`;
      const customerName = msg.pushName || "WhatsApp Customer";

      // 5. Extract text content
      let text =
        msg.message?.conversation ||
        msg.message?.extendedTextMessage?.text ||
        msg.message?.imageMessage?.caption ||
        msg.message?.documentMessage?.caption ||
        msg.message?.videoMessage?.caption ||
        "";

      if (!text.trim()) return;

      this.lastInboundTime = new Date().toISOString();
      console.log(`[WA_SESSION] INBOUND from ${customerPhone} (${customerName}): "${text}"`);

      // 6. Normalize into ChannelMessage
      const channelMsg: ChannelMessage = {
        messageId,
        conversationId: customerPhone,
        from: customerPhone,
        to: this.connectedPhone || "QuickReply",
        text,
        timestamp: new Date((Number(msg.messageTimestamp) || Date.now() / 1000) * 1000).toISOString(),
        platform: "whatsapp",
        rawPayload: msg,
      };

      // 7. Execute any registered external message listeners
      for (const listener of this.messageListeners) {
        try {
          await listener(channelMsg);
        } catch (lErr) {
          console.error("[WA_SESSION] Listener error:", lErr);
        }
      }

      // 8. Process through the real QuickReply AI Automation Engine
      const db = await getDB();
      const aiResult = await processWhatsAppMessage({
        waMessageId: messageId,
        conversationId: channelMsg.conversationId,
        customerPhone,
        customerName,
        text,
        timestamp: channelMsg.timestamp,
        db,
        organizationId: "org_default",
      });

      // Save generated messages & analytics to DB
      if (aiResult.newMessages && aiResult.newMessages.length > 0) {
        if (!db.waMessages) db.waMessages = [];
        db.waMessages.push(...aiResult.newMessages);
      }
      if (aiResult.analyticsEvents && aiResult.analyticsEvents.length > 0) {
        if (!db.waAnalyticsEvents) db.waAnalyticsEvents = [];
        db.waAnalyticsEvents.push(...aiResult.analyticsEvents);
      }
      await saveDB(db);

      // 9. If AI generated a reply, escalation was not triggered, and auto-reply is enabled, send real reply back
      if (aiResult.shouldSend && aiResult.responseText && db.waSettings?.autoReply && db.waSettings?.enabled) {
        console.log(`[WA_SESSION] Sending automated AI reply to ${customerPhone}: "${aiResult.responseText.substring(0, 60)}..."`);
        await this.sendMessage(customerPhone, aiResult.responseText);
      }

      // 10. Broadcast message arrival to dashboard
      broadcastEvent("whatsapp.message_received", {
        messageId,
        customerPhone,
        text,
        timestamp: channelMsg.timestamp,
        reply: aiResult.responseText || undefined,
        intent: aiResult.intent,
        confidence: aiResult.confidence,
      });
    } catch (err) {
      console.error("[WA_SESSION] Inbound message processing error:", err);
    }
  }

  /**
   * Send a real text message via the Baileys multi-device socket
   */
  async sendMessage(to: string, text: string): Promise<SendResult> {
    if (!this.socket || this.state !== "CONNECTED") {
      return { success: false, error: "WhatsApp is not connected" };
    }

    try {
      const cleanDigits = to.replace(/\D/g, "");
      const jid = `${cleanDigits}@s.whatsapp.net`;

      const result = await this.socket.sendMessage(jid, { text });
      const outMessageId = result?.key?.id || `out_${Date.now()}`;
      this.lastOutboundTime = new Date().toISOString();

      console.log(`[WA_SESSION] OUTBOUND sent to ${to}: "${text.substring(0, 80)}..." (ID: ${outMessageId})`);

      broadcastEvent("whatsapp.message_sent", {
        messageId: outMessageId,
        to,
        text,
        timestamp: this.lastOutboundTime,
      });

      return {
        success: true,
        messageId: outMessageId,
      };
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : "Failed to send WhatsApp message";
      console.error(`[WA_SESSION] Send error to ${to}:`, err);
      return { success: false, error: errMsg };
    }
  }

  /**
   * Send media message
   */
  async sendMedia(to: string, media: MediaPayload): Promise<SendResult> {
    if (!this.socket || this.state !== "CONNECTED") {
      return { success: false, error: "WhatsApp is not connected" };
    }

    try {
      const cleanDigits = to.replace(/\D/g, "");
      const jid = `${cleanDigits}@s.whatsapp.net`;

      let content: Record<string, unknown> = {};
      if (media.type === "image" && media.url) {
        content = { image: { url: media.url }, caption: media.caption || "" };
      } else if (media.type === "document" && media.url) {
        content = { document: { url: media.url }, fileName: media.filename || "document.pdf", caption: media.caption || "" };
      }

      const result = await this.socket.sendMessage(jid, content as any);
      return { success: true, messageId: result?.key?.id || undefined };
    } catch (err) {
      return { success: false, error: err instanceof Error ? err.message : "Media send error" };
    }
  }

  async sendTemplate(to: string, _template: TemplatePayload): Promise<SendResult> {
    return this.sendMessage(to, "Template message not supported in Web session mode.");
  }

  async getConversation(id: string): Promise<ChannelConversation | null> {
    return { id, participants: [id, this.connectedPhone || ""], lastMessageAt: new Date().toISOString() };
  }

  async markRead(messageId: string): Promise<void> {
    if (this.socket) {
      try {
        await this.socket.readMessages([{ id: messageId }]);
      } catch {}
    }
  }

  async getCustomer(id: string): Promise<ChannelCustomer | null> {
    return { id, phone: id };
  }

  async createWebhook(_config: WebhookConfig): Promise<string> {
    return "baileys_socket_internal";
  }

  async validateWebhook(_request: Request): Promise<boolean> {
    return true;
  }

  async handleEvent(_event: ChannelEvent): Promise<void> {}

  async receiveMessage(payload: unknown): Promise<ChannelMessage> {
    const p = payload as ChannelMessage;
    return p;
  }

  /**
   * Terminate active WhatsApp session and clean up authentication tokens
   */
  async disconnect(): Promise<{ success: boolean; error?: string }> {
    try {
      console.log("[WA_SESSION] Terminating WhatsApp session...");
      if (this.socket) {
        try {
          await this.socket.logout();
        } catch {}
        try {
          this.socket.end(new Error("Manual disconnect"));
        } catch {}
        this.socket = null;
      }

      this.cleanupAuthFiles();

      this.state = "DISCONNECTED";
      this.connectedPhone = null;
      this.pushName = null;
      this.connectedTimestamp = null;
      this.rawQR = null;
      this.qrDataUrl = null;

      broadcastEvent("whatsapp.disconnected", { reason: "manual_disconnect" });
      this.broadcastStatus();

      return { success: true };
    } catch (err) {
      const error = err instanceof Error ? err.message : "Failed to disconnect";
      return { success: false, error };
    }
  }

  private cleanupAuthFiles(): void {
    try {
      if (fs.existsSync(this.activeMetaFile)) {
        fs.unlinkSync(this.activeMetaFile);
      }
      if (fs.existsSync(this.authDir)) {
        fs.rmSync(this.authDir, { recursive: true, force: true });
        fs.mkdirSync(this.authDir, { recursive: true });
      }
    } catch (err) {
      console.error("[WA_SESSION] Cleanup error:", err);
    }
  }

  private broadcastStatus(): void {
    broadcastEvent("wa:status:update", this.getStatus());
  }

  getStatus(): ChannelStatus {
    const isConn = this.state === "CONNECTED" && !!this.connectedPhone;
    return {
      connected: isConn,
      status: this.state.toLowerCase() as ChannelStatus["status"],
      phone: this.connectedPhone || undefined,
      businessName: this.pushName || undefined,
      provider: "whatsapp_web_session",
      qrCode: this.qrDataUrl || undefined,
      uptime: this.connectedTimestamp ? Date.now() - this.connectedTimestamp : undefined,
      lastConnectedAt: this.connectedTimestamp ? new Date(this.connectedTimestamp).toISOString() : undefined,
      lastMessageReceivedAt: this.lastInboundTime || undefined,
      lastMessageSentAt: this.lastOutboundTime || undefined,
    };
  }

  getQRCode(): string | null {
    return this.qrDataUrl;
  }

  getDebugDiagnostics() {
    return {
      provider: "Baileys WhatsApp Multi-Device (WebSockets)",
      sessionExists: fs.existsSync(this.authDir) && fs.readdirSync(this.authDir).length > 0,
      sessionState: this.state,
      socketConnected: !!this.socket && this.state === "CONNECTED",
      qrAvailable: !!this.qrDataUrl,
      phone: this.connectedPhone,
      pushName: this.pushName,
      connectedAt: this.connectedTimestamp ? new Date(this.connectedTimestamp).toISOString() : null,
      lastInbound: this.lastInboundTime,
      lastOutbound: this.lastOutboundTime,
      lastError: this.lastError,
      registeredListeners: this.messageListeners.length,
    };
  }
}
